name: GitHub Pages
permissions:
  contents: read

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * *'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install documentation requirements
        run: |
          pip install -r docs/requirements.txt

      - name: Make docs builds
        run: |
          make -C docs html O="-t release"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
